### ISSUE TITLE
why do you websocket

### ISSUE THREAD

**Issue by fizz12344321** [babl-ws/babl#115]
Hi, why do you use Websocket, why don't you use Rsocket to increase performance. And can you share me some factors to achieve High Performance app ?

**Comment by epickrram** [comment]
Hi @fizz12344321 
this project implements the WebSocket protocol because that was the aim of the project.
RSocket is a protocol that could be implemented over the WebSocket transport. It would be possible to layer an RSocket implementation on top of babl's WebSocket support, but that is not a goal of the project.

There are many good resources available on the internet detailing how to write high performance software. Without knowing anything about your planned application, it's difficult to suggest anything that might help you.
